Update requirements.txt
Fixed open3D version 0.9 does not exist.

"ERROR: Could not find a version that satisfies the requirement opencd==0.9 (from versions: none)
ERROR: No matching distribution found for opencd==0.9"